module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'jest-environment-node',
  testMatch: ['**/__tests__/**/*.unit.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/index.ts',
    '!src/**/config.ts',
    '!**/*.fixture.ts',
    '!**/*.mock.ts',
    '!**/*.error.ts',
    '!**/__tests__/**',
    '!src/**/*.enums.ts',
    '!src/**/*.types.ts',
    '!src/errors.ts',
    '!src/enums.ts',
    '!src/types.ts',
    '!src/broadcast.client.ts',
    '!src/broadcast.server.ts',
  ],
};
